- name: test
  hosts: all
  become: true
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"
  tasks:
    - debug:
        msg: "private ip is {{ foo }}"
    - debug:
        msg: "instance_id is {{ boo }}"
    - debug:
        msg: "my key pem is {{ key }}"
    - debug:
        msg: "host is {{ ansible_host }}"
    - debug:
        msg: "my key pem is {{ key }}"